// const countries = [
//   { name: 'Australia', capital: 'Canberra' },
//   { name: 'Brazil', capital: 'Brasília' },
//   { name: 'Canada', capital: 'Ottawa' },
//   { name: 'China', capital: 'Beijing' },
//   { name: 'France', capital: 'Paris' },
//   { name: 'India', capital: 'New Delhi' },
//   { name: 'Italy', capital: 'Rome' },
//   { name: 'Japan', capital: 'Tokyo' },
//   { name: 'Mexico', capital: 'Mexico City' },
//   { name: 'Russia', capital: 'Moscow' },
//   { name: 'South Africa', capital: 'Pretoria' },
//   { name: 'United Kingdom', capital: 'London' },
//   { name: 'United States', capital: 'Washington D.C.' },
// ];
